[[redirects]]
  from = "/favicon.ico"
  to = "/assets/favicon-32.png"
  status = 200

[[redirects]]
  from = "/trgovina/bradovec-tinktura/"
  to = "/trgovina/resasti-bradovec-tinktura/"
  status = 301

[[redirects]]
  from = "/trgovina/smrekovi-vrsicki/"
  to = "/trgovina/smrekovi-vrsicki-tinktura/"
  status = 301

[[redirects]]
  from = "/znanje/beta-glukani-medicinske-gobe/"
  to = "/znanje/beta-glukani/"
  status = 301
  force = true

[[redirects]]
  from = "/qc/tezke-kovine"
  to = "/qc/tezke-kovine/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/en/shop/lions-mane-tincture/"
  to = "/trgovina/resasti-bradovec-tinktura/"
  status = 301
  force = true

[[redirects]]
  from = "/qc/heavy-metals/"
  to = "/en/qc/heavy-metals/"
  status = 301
  force = true

[[redirects]]
  from = "/qc/tezke-kovine/PATH/*"
  to = "/qc/tezke-kovine/"
  status = 301
  force = true

[[redirects]]
  from = "/showroom_*"
  to = "/404.html"
  status = 404
  force = true