[[redirects]]
  from = "/favicon.ico"
  to = "/assets/favicon-32.png"
  status = 200

[[redirects]]
  from = "/trgovina/bradovec-tinktura/"
  to = "/trgovina/resasti-bradovec-tinktura/"
  status = 301

[[redirects]]
  from = "/trgovina/smrekovi-vrsicki/"
  to = "/trgovina/smrekovi-vrsicki-tinktura/"
  status = 301

[[redirects]]
  from = "/znanje/beta-glukani-medicinske-gobe/"
  to = "/znanje/beta-glukani/"
  status = 301
  force = true

[[redirects]]
  from = "/qc/tezke-kovine"
  to = "/qc/tezke-kovine/"
  status = 301

